config/routes.rb
Rails.application.routes.draw do

  resources :students
  resources :projects
  resources :faqs

  root 'students#featured'

end

app/models/faq.rb
class Faq < ActiveRecord::Base

end

app/models/project.rb
class Project < ActiveRecord::Base
	has_many :students

	has_attached_file :screenshot, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  	validates_attachment_content_type :screenshot, :content_type => /\Aimage\/.*\Z/

end

app/models/student.rb
class Student < ActiveRecord::Base
	belongs_to :project

	has_attached_file :pic, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
    validates_attachment_content_type :pic, :content_type => /\Aimage\/.*\Z/


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/faqs_controller.rb
class FaqsController < ApplicationController
	before_action :set_faq, only: [:show, :edit, :update, :destroy]

	def index
		@faqs = Faq.all
	end



	def new
		@faq = Faq.new
	end



	def create
		@faq = Faq.create(faq_params)

		redirect_to faqs_path
	end



	def show		
	end



	def edit	
	end




	def update
		respond_to do |format|
    	if @faq.update(faq_params)
        	format.html { redirect_to @faq, notice: 'Project was successfully updated.' }
        else
        	format.html { render :edit }
      	end
    	end
	end



	def destroy
		@faq.destroy

		redirect_to :back
	end



	private

	def set_faq
		@faq = Faq.find(params[:id])
	end

	def faq_params
		params.require(:faq).permit(:question, :answer)
	end


end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	before_action :set_project, only: [:show, :edit, :update, :destroy]

	def index
		@projects = Project.all
	end



	def new
		@project = Project.new
	end



	def create
		@project = Project.create(project_params)
		redirect_to projects_path
	end



	def show		
	end



	def edit	
	end




	def update
		respond_to do |format|
    	if @project.update(project_params)
        	format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        else
        	format.html { render :edit }
      	end
    	end
	end



	def destroy
		@project.destroy

		redirect_to :back
	end



	private

	def set_project
		@project = Project.find(params[:id])
	end

	def project_params
		params.require(:project).permit(:name, :url, :description, :screenshot)
	end


end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
	before_action :set_student, only: [:show, :edit, :update, :destroy]


	def index
		@students = Student.all
	end



	def new
		@student = Student.new
		@schools = Hash.new([])
		@schools["Barnard College"] = "ff-barnard-college"
		@schools["Dartmouth College"] = "ff-dartmouth-college"
		@schools["Georgetown University"] = "ff-georgetown-university"
		@schools["Harvard University"] = "ff-harvard-university"
		@schools["Standford University"] = "ff-standford-university"
		@schools["University of Georgia"] = "ff-university-of-georgia"
		@schools["University of Michigan"] = "ff-university-of-michigan"
		@schools["University of Southern California"] = "ff-university-of-southern-california"
		@schools["University of Virginia"] = "ff-university-of-virginia"
		@schools["Yale University"] = "ff-yale-university"
		@projects = Hash.new([])
		Project.all.each do |project| 
			@projects[project.name] = project.id
		end

	end



	def create
		@student = Student.create(student_params)

		redirect_to students_path
	end



	def show
	end



	def edit
		@schools = Hash.new([])
		@schools["Barnard College"] = "ff-barnard-college"
		@schools["Dartmouth College"] = "ff-dartmouth-college"
		@schools["Georgetown University"] = "ff-georgetown-university"
		@schools["Harvard University"] = "ff-harvard-university"
		@schools["Standford University"] = "ff-standford-university"
		@schools["University of Georgia"] = "ff-university-of-georgia"
		@schools["University of Michigan"] = "ff-university-of-michigan"
		@schools["University of Southern California"] = "ff-university-of-southern-california"
		@schools["University of Virginia"] = "ff-university-of-virginia"
		@schools["Yale University"] = "ff-yale-university"
		@projects = Hash.new([])
		Project.all.each do |project| 
			@projects[project.name] = project.id
		end
	end



	def update
		respond_to do |format|
    	if @student.update(student_params)
        	format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        else
        	format.html { render :edit }
      	end
    	end
		
	end



	def destroy
		@student.destroy

		redirect_to :back
	end



	def featured
		@students = Student.all
	end




	private

	def set_student
		@student = Student.find(params[:id])
	end


	def student_params
		params.require(:student).permit(:first_name, :last_name, :school, :year, :major, :email, :github, :about, :quote, :project_id, :pic)
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/faqs/_faq_form.html.erb
<%= form_for(@faq) do |f| %>
	<%= f.label :question %>
	<%= f.text_field :question %>
	<br/><br/>

	<%= f.label :answer %>
	<%= f.text_field :answer %>
	<br/><br/>

	<%= f.submit %>
<% end %>

app/views/faqs/edit.html.erb
<h1>Editing FAQ</h1>

<%= render 'faq_form' %>

<%= link_to 'Show', faq_path %> |
<%= link_to 'Back', faqs_path %>

app/views/faqs/index.html.erb
<div class="container">

	<div id="faq_page_title">
		<h1>FAQ Answered by Alumni</h1>
	</div>

	<section id="fa_container" class="fa_container">

		<ul id="fa_list">
			<% @faqs.each do |faq| %>
				<li>

					<div class="fa_question" id=<%="#{faq.id}"%>>
						<%= faq.question %>
					</div>
					
					<div class="fa_answer" id=<%="fa_answer#{faq.id}"%>>
						<%= faq.answer %>
					</div>

				</li>
			<% end %>
		</ul>
			

	</section>
	
</div>

app/views/faqs/new.html.erb
<h1>New FAQ</h1>

<%= render 'faq_form' %>

app/views/faqs/show.html.erb
<p>
	<strong>Question:</strong>
	<%= @faq.question %>
</p>

<p>
	<strong>Answer:</strong>
	<%= @faq.answer %>
</p>


<%= link_to 'Edit', edit_faq_path(@faq) %>  |  
<%= link_to 'Back', faqs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en" class="no-js">
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"> 
		<meta name="viewport" content="width=device-width, initial-scale=1.0"> 
		<title>IX Alumni</title>
		<!-- <link rel="shortcut icon" href="../favicon.ico"> -->

		<%= stylesheet_link_tag    'normalize' %>
		<%= stylesheet_link_tag    'application' %>
		<%= stylesheet_link_tag    'icons' %>
		<%= stylesheet_link_tag    'menu' %>
		<%= stylesheet_link_tag    'featured' %>
  		<%= stylesheet_link_tag    'jquery.jscrollpane' %>
  		<%= stylesheet_link_tag    'faq' %>
  		<%= stylesheet_link_tag    'project' %>
  		<%= stylesheet_link_tag    'filter' %>



  		<%= javascript_include_tag 'modernizr.custom' %>
  		<%= javascript_include_tag 'application' %>

  		
  		<%= javascript_include_tag 'modernizr.custom.29473' %>
  		<%= javascript_include_tag 'modernizr.custom.53451' %>
  		
  		
  		
  		<%= csrf_meta_tags %>
	</head>
	<body>
		<div class="container1">
			
			<%= yield %>


			<nav id="bt-menu" class="bt-menu">
				<a href="#" class="bt-menu-trigger"><span>Menu</span></a>
				<ul>
					<li><%= link_to 'Home', root_path %></li>
					<li><%= link_to 'Projects', projects_path %></li>
					<li><%= link_to 'FAQ', faqs_path %></li>
					<li><%= link_to 'Contact', students_path %></li>
					<!-- <li><a href="#" class="bt-icon icon-windows">FAQ</a></li> -->
					<!-- <li><a href="#" class="bt-icon icon-speaker">Contact</a></li> -->
					<li><a href="#" class="bt-icon icon-star">Gallery</a></li>
					<li><a href="#" class="bt-icon icon-bubble">Other</a></li>
				</ul>
			</nav>
		</div><!-- /container -->
	</body>

	<%= javascript_include_tag 'classie' %>
	<%= javascript_include_tag 'borderMenu' %>

	<!-- the featured page work with this -->
	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
	<%= javascript_include_tag 'jquery.easing.1.3' %>	
	<!-- the jScrollPane script -->
	<%= javascript_include_tag 'jquery.mousewheel' %>
	<%= javascript_include_tag 'jquery.contentcarousel' %>

	<%= javascript_include_tag 'jquery.gallery' %>



	<script type="text/javascript">

		$(function() {
			$('#dg-container').gallery();
		});

		$('#ca-container').contentcarousel();

	</script/>


</html>

app/views/projects/_project_form.html.erb
<%= form_for(@project) do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<br/><br/>

	<%= f.label :link %>
	<%= f.text_field :url %>
	<br/><br/>

	<%= f.label :description %>
	<%= f.text_field :description %>
	<br/><br/>

	<%= f.label :screenshot %>
	<%= f.file_field :screenshot %>
	<br/><br/>

	<%= f.submit %>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'project_form' %>

<%= link_to 'Show', project_path %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<div id="project_page_title">
 	<h1>IX Past Projects</h1>
</div>

 <div class="container">
			
	<section id="dg-container" class="dg-container">
		<div class="dg-wrapper">

			<% @projects.each do |project| %>
				<li>
					<%= image_tag project.screenshot %>
					<div id="project_info">
						<%= project.url %>
						<% project.students.each do |student| %>
							<span><%= student.first_name + " " %></span>
						<% end %>
					</div>
				</li>
			<% end %>
			
		</div>

		<nav>	
			<span class="dg-prev">&lt;</span>
			<span class="dg-next">&gt;</span>
		</nav>

	</section>
</div>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'project_form' %>

app/views/projects/show.html.erb
<p>
	<strong>Name:</strong>
	<%= @project.name %>
</p>

<p>
	<strong>Link:</strong>
	<%= @project.url %>
</p>

<p>
	<strong>Description:</strong>
	<%= @project.description %>
</p>


<%= link_to 'Edit', edit_project_path(@project) %>  |  
<%= link_to 'Back', projects_path %>

app/views/students/_student_form.html.erb
<%= form_for(@student, :html => { :multipart => true }) do |f| %>
	<%= f.label :first_name %>
	<%= f.text_field :first_name %>
	<br/><br/>

	<%= f.label :last_name %>
	<%= f.text_field :last_name %>
	<br/><br/>

	<%= f.label :school %>
	<%= f.select :school, @schools %>

	<%= f.label :year %>
	<%= f.text_field :year %>
	<br/><br/>

	<%= f.label :major %>
	<%= f.text_field :major %>
	<br/><br/>

	<%= f.label :email %>
	<%= f.text_field :email %>
	<br/><br/>

	<%= f.label :github %>
	<%= f.text_field :github %>
	<br/><br/>

	<%= f.label :about %>
	<%= f.text_field :about %>
	<br/><br/>

	<%= f.label :quote %>
	<%= f.text_field :quote %>
	<br/><br/>

	<%= f.label :project %>
	<%= f.select :project_id, @projects %>
	<br/><br/>

	<%= f.label :profile_picture %>
	<%= f.file_field :pic %>
	<br/><br/>

	<%= f.submit %>
<% end %>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'student_form' %>

<%= link_to 'Show', student_path %> |
<%= link_to 'Back', students_path %>

app/views/students/featured.html.erb
<div class="container">

	<h1>Featured Alumni</h1>
			
	<div id="ca-container" class="ca-container">
		<div class="ca-wrapper">

			<div class="ca-item ca-item-1">
				<div class="ca-item-main">
					<div class="ca-icon"><%= image_tag @students[0].pic%></div>
					<h3><%= @students[0].first_name + " " + @students[0].last_name %></h3>
					<h4>
						<p><%= @students[0].school %></p>
						<p><%= "Class of " + @students[0].year %></p>
						<div class="ca-border">
							<span class="ca-quote">&ldquo;</span>
							<span><%= @students[0].quote %></span>
						</div>
					</h4>
						<a href="#" class="ca-more">more...</a>
				</div>
				<div class="ca-content-wrapper">
					<div class="ca-content">
						<h6><%= @students[0].first_name + " " + @students[0].last_name %></h6>
						<a href="#" class="ca-close"><%= image_tag 'cross.png' %></a>
						<div class="ca-content-text">
							<p>I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents. I should be incapable of drawing a single stroke at the present moment; and yet I feel that I never was a greater artist than now.</p>
							<p>When, while the lovely valley teems with vapour around me, and the meridian sun strikes the upper surface of the impenetrable foliage of my trees, and but a few stray gleams steal into the inner sanctuary, I throw myself down among the tall grass by the trickling stream;</p>
							<p>She packed her seven versalia, put her initial into the belt and made herself on the way.</p>
						</div>
						
					</div>
				</div>
			</div>




			<div class="ca-item ca-item-2">
				<div class="ca-item-main">
					<div class="ca-icon"><%= image_tag @students[1].pic%></div>
					<h3><%= @students[1].first_name + " " + @students[1].last_name %></h3>
					<h4>
						<p><%= @students[1].school %></p>
						<p><%= "Class of " + @students[1].year %></p>
						<div class="ca-border">
							<span class="ca-quote">&ldquo;</span>
							<span><%= @students[2].quote %></span>
						</div>
					</h4>
						<a href="#" class="ca-more">more...</a>
				</div>
				<div class="ca-content-wrapper">
					<div class="ca-content">
						<h6><%= @students[1].first_name + " " + @students[1].last_name %></h6>
						<a href="#" class="ca-close"><%= image_tag 'cross.png' %></a>
						<div class="ca-content-text">
							<p>I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents. I should be incapable of drawing a single stroke at the present moment; and yet I feel that I never was a greater artist than now.</p>
							<p>When, while the lovely valley teems with vapour around me, and the meridian sun strikes the upper surface of the impenetrable foliage of my trees, and but a few stray gleams steal into the inner sanctuary, I throw myself down among the tall grass by the trickling stream;</p>
							<p>She packed her seven versalia, put her initial into the belt and made herself on the way.</p>
						</div>
						
					</div>
				</div>
			</div>








			<div class="ca-item ca-item-3">
				<div class="ca-item-main">
					<div class="ca-icon"><%= image_tag @students[2].pic%></div>
					<h3><%= @students[2].first_name + " " + @students[2].last_name %></h3>
					<h4>
						<p><%= @students[2].school %></p>
						<p><%= "Class of " + @students[2].year %></p>
						<div class="ca-border">
							<span class="ca-quote">&ldquo;</span>
							<span><%= @students[2].quote %></span>
						</div>
					</h4>
						<a href="#" class="ca-more">more...</a>
				</div>
				<div class="ca-content-wrapper">
					<div class="ca-content">
						<h6><%= @students[2].first_name + " " + @students[2].last_name %></h6>
						<a href="#" class="ca-close"><%= image_tag 'cross.png' %></a>
						<div class="ca-content-text">
							<p>I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents. I should be incapable of drawing a single stroke at the present moment; and yet I feel that I never was a greater artist than now.</p>
							<p>When, while the lovely valley teems with vapour around me, and the meridian sun strikes the upper surface of the impenetrable foliage of my trees, and but a few stray gleams steal into the inner sanctuary, I throw myself down among the tall grass by the trickling stream;</p>
							<p>She packed her seven versalia, put her initial into the belt and made herself on the way.</p>
						</div>
						
					</div>
				</div>
			</div>







			<div class="ca-item ca-item-4">
				<div class="ca-item-main">
					<div class="ca-icon"><%= image_tag @students[3].pic%></div>
					<h3><%= @students[3].first_name + " " + @students[3].last_name %></h3>
					<h4>
						<p><%= @students[3].school %></p>
						<p><%= "Class of " + @students[3].year %></p>
						<div class="ca-border">
							<span class="ca-quote">&ldquo;</span>
							<span><%= @students[3].quote %></span>
						</div>
					</h4>
						<a href="#" class="ca-more">more...</a>
				</div>
				<div class="ca-content-wrapper">
					<div class="ca-content">
						<h6><%= @students[3].first_name + " " + @students[3].last_name %></h6>
						<a href="#" class="ca-close"><%= image_tag 'cross.png' %></a>
						<div class="ca-content-text">
							<p>I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents. I should be incapable of drawing a single stroke at the present moment; and yet I feel that I never was a greater artist than now.</p>
							<p>When, while the lovely valley teems with vapour around me, and the meridian sun strikes the upper surface of the impenetrable foliage of my trees, and but a few stray gleams steal into the inner sanctuary, I throw myself down among the tall grass by the trickling stream;</p>
							<p>She packed her seven versalia, put her initial into the belt and made herself on the way.</p>
						</div>
						
					</div>
				</div>
			</div>






			<div class="ca-item ca-item-5">
				<div class="ca-item-main">
					<div class="ca-icon"><%= image_tag @students[4].pic%></div>
					<h3><%= @students[4].first_name + " " + @students[4].last_name %></h3>
					<h4>
						<p><%= @students[4].school %></p>
						<p><%= "Class of " + @students[4].year %></p>
						<div class="ca-border">
							<span class="ca-quote">&ldquo;</span>
							<span><%= @students[4].quote %></span>
						</div>
					</h4>
						<a href="#" class="ca-more">more...</a>
				</div>
				<div class="ca-content-wrapper">
					<div class="ca-content">
						<h6><%= @students[4].first_name + " " + @students[4].last_name %></h6>
						<a href="#" class="ca-close"><%= image_tag 'cross.png' %></a>
						<div class="ca-content-text">
							<p>I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents. I should be incapable of drawing a single stroke at the present moment; and yet I feel that I never was a greater artist than now.</p>
							<p>When, while the lovely valley teems with vapour around me, and the meridian sun strikes the upper surface of the impenetrable foliage of my trees, and but a few stray gleams steal into the inner sanctuary, I throw myself down among the tall grass by the trickling stream;</p>
							<p>She packed her seven versalia, put her initial into the belt and made herself on the way.</p>
						</div>
						
					</div>
				</div>
			</div>
	

		</div>				
	</div>
			
</div>

app/views/students/index.html.erb
<div class="container">

	<div id="alumni_contact_title">
		<h1>Meet An IX Alumni</h1>
	</div>
	
	<section class="ff-container">

			<input id="select-type-all" name="student-school" type="radio" class="ff-selector-type-all" checked="checked" />
			<label for="select-type-all" class="ff-label-type-all">All</label>

			<input id="barnard-college" name="student-school" type="radio" class="ff-barnard-college" />
			<label for="barnard-college" class="ff-label-barnard-college">Barnard College</label>

			<input id="dartmouth-college" name="student-school" type="radio" class="ff-dartmouth-college" />
			<label for="dartmouth-college" class="ff-label-dartmouth-college">Dartmouth College</label>

			<input id="georgetown-university" name="student-school" type="radio" class="ff-georgetown-university">
			<label for="georgetown-university" class="ff-label-georgetown-university">Georgetown University</label>
			
			<input id="harvard-university" name="student-school" type="radio" class="ff-harvard-university" />
			<label for="harvard-university" class="ff-label-harvard-university">Harvard University</label>

			<input id="standford-university" name="student-school" type="radio" class="ff-standford-university">
			<label for="standford-university" class="ff-label-standford-university">Standford University</label>

			<input id="university-of-georgia" name="student-school" type="radio" class="ff-university-of-georgia">
			<label for="university-of-georgia" class="ff-label-university-of-georgia">University of Georgia</label>

			<input id="university-of-michigan" name="student-school" type="radio" class="ff-university-of-michigan" />
			<label for="university-of-michigan" class="ff-label-university-of-michigan">University of Michigan</label>

			<input id="university-of-southern-california" name="student-school" type="radio" class="ff-university-of-southern-california">
			<label for="university-of-southern-california" class="ff-label-university-of-southern-california">University Of Southern California</label>

			<input id="university-of-virginia" name="student-school" type="radio" class="ff-university-of-virginia">
			<label for="university-of-virginia" class="ff-label-university-of-virginia">University of Virginia</label>
			
			<input id="yale-university" name="student-school" type="radio" class="ff-yale-university" />
			<label for="yale-university" class="ff-label-yale-university">Yale University</label>
		
		<div class="clr"></div>

		<ul class="ff-items">
			<% @students.each do |student| %>
				<li class="<%= student.school %>">
					<%= image_tag student.pic %>
					<p><%= student.first_name + " " + student.last_name %></p>


					<button class="btn btn-primary btn-lg" data-toggle="modal" data-target="#<%= student.id %>">
						Read More
					</button>

					<!-- Modal -->
					<div class="modal fade" id="<%= student.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
					  <div class="modal-dialog">
					    <div class="modal-content">
					      <div class="modal-header">
					        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
					        <h4 class="modal-title" id="myModalLabel"><%= "Grab a coffee with " + student.first_name %></h4>
					      </div>
					      <div class="modal-body">
					      	<%= image_tag student.pic %>
					        <%= student.first_name %><br>
					        <%= "Email: " + student.email %>
					      </div>
					      <div class="modal-footer">
					        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
					        <button type="button" class="btn btn-primary">Send Message</button>
					      </div>
					    </div>
					  </div>
					</div>

				</li>


			<% end %>

		</ul>


		


		


	</section>
</div>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'student_form' %>

app/views/students/show.html.erb
<p>
	<strong>First Name:</strong>
	<%= @student.first_name %>
</p>

<p>
	<strong>Last Name:</strong>
	<%= @student.last_name %>
</p>

<p>
	<strong>School:</strong>
	<%= @student.school %>
</p>

<p>
	<strong>Profile Picture:</strong>
	<%= image_tag @student.pic.url(:thumb) %>
</p>




<%= link_to 'Edit', edit_student_path(@student) %>  |  
<%= link_to 'Back', students_path %>